# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test and Publish WebAPi Container Image

on:
  push:
    branches: [ "main" ]
    tags: [ "v1*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  {} # allow manually trigger workflow

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Get Go version from go.mod
      id: get_go_version
      run: echo "go_version=$(grep -m1 'go ' go.mod | awk '{print $2}')" >> $GITHUB_OUTPUT

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ steps.get_go_version.outputs.go_version }}
        
    - name: Generate api controllers interfaces
      uses: craicoverflow/openapi-generator-generate-action@v1.2.1
      with:
        generator: go-gin-server
        input: api/consulting.openapi.yaml
        additional-properties: apiPath=internal/consulting,packageName=consulting,interfaceOnly=true
        
    - name: Build
      run: go build -v ./cmd/api-service

    - name: Test
      run: go test -v ./...

    - name: Docker Setup QEMU
      # You may pin to the exact commit or the version.
      # uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392
      uses: docker/setup-qemu-action@v3.6.0

    - name: Docker Setup Buildx
      # You may pin to the exact commit or the version.
      # uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2
      uses: docker/setup-buildx-action@v3.10.0
      
    - name: Docker Metadata action
      id: meta
      uses: docker/metadata-action@v5.7.0
      with:
        images: xtodorovicm/mt-consulting-webapi
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=branch,suffix={{date '.YYYYMMDD.HHmm'}}
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.15.0
      with:
        context: .
        file: ./build/docker/Dockerfile
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: ${{ steps.meta.outputs.tags }}
